### ISSUE TITLE
Why not auto cancel grpc call during teardown?

### ISSUE THREAD

**Issue by N0N4M3pl** [wisetime-io/grpc-web-rx#2]
I have question about this code (from `client.ts `):
```
export const from = <T>(
  rpc: UnaryRpc<T> | ServerStreamingRpc
): Observable<T> =>
    new Observable<T>(observer => {
      const call = rpc()
      if (isServerStreaming<T>(call)) {
        fromServerStreaming(call, observer)
      } else {
        fromUnary(call, observer)
      }
    })
```

Why not auto close grpc call?
So it will be:
```
export const from = <T>(
  rpc: UnaryRpc<T> | ServerStreamingRpc
): Observable<T> =>
    new Observable<T>(observer => {
      const call = rpc()
      if (isServerStreaming<T>(call)) {
        fromServerStreaming(call, observer)
      } else {
        fromUnary(call, observer)
      }
      return () => {
        call.close()
      };
    })
```

Maybe its not a bug (but feature ;-) ) - I'm only asking.

**Comment by j4ckofalltrades** [comment]
The resulting type of `const call = rpc()` is `Promise<T> | grpcWeb.ClientReadableStream<unknown>` both of which do not have a `close()` function.

A unary RPC returns a [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises) that will either resolve or fail.

```javascript
var request = new proto.mypackage.EchoRequest();
request.setMessage(msg);
var metadata = {'custom-header-1': 'value1'};
echoService.echo(request, metadata, function(err, response) {
  if (err) {
    console.log(err.code);
    console.log(err.message);
  } else {
    console.log(response.getMessage());
  }
});
```

While a server-streaming RPC returns a [ClientReadableStream](https://github.com/grpc/grpc-web/blob/master/javascript/net/grpc/web/clientreadablestream.js) that uses events to signal if data has arrived or if the stream has ended.

```javascript
var stream = echoService.serverStreamingEcho(streamRequest, metadata);
stream.on('data', function(response) {
  console.log(response.getMessage());
});
stream.on('status', function(status) {
  console.log(status.code);
  console.log(status.details);
  console.log(status.metadata);
});
stream.on('end', function(end) {
  // stream end signal
});
```

**Comment by N0N4M3pl** [comment]
> The resulting type of const call = rpc() is Promise<T> | grpcWeb.ClientReadableStream<unknown> both of which do not have a close() function.

This is understandable. I focused only on stream request.  
Maybe in future there should be 2 operators: `fromUnrary` and `fromStream`.

My question is how You execute call.close() outside `from`?  
If `from` create `const call` inside Observer (on first subscription) then it is scoped inside.  
In my code I have to use `from` like this:  
```
this.stream$ = from<T>(() => {
   return this.grpcStream = this.grpcStreamBuilder(toSubscribe);
}).pipe(retry(this.policy));
```
I intercepts instance of ClientReadableStream and hold it in this.grpcStream.   
When subsciption is over then I call `this.grpcStream.close()`.

In my opinion better option will be autoclose stream when no one is subscribed.  
It can be done only in Teardown function which is declared in Observer construction:  
```
new Observable<T>(observer => {
   const call = rpc();
   ...
   return () => {
     call.close()
   };
});
```

**Comment by j4ckofalltrades** [comment]
To reiterate [ClientReadableStream](https://github.com/grpc/grpc-web/blob/master/javascript/net/grpc/web/clientreadablestream.js) has no `close()` function. The "call" ends when the stream emits the "end" event.

**Comment by N0N4M3pl** [comment]
You are right - there is no `close()` method.  
I meant `cancel()` : https://github.com/grpc/grpc-web/blob/master/javascript/net/grpc/web/clientreadablestream.js#L86

**Comment by j4ckofalltrades** [comment]
You can manually close the stream from your function that has the `ClientReadableStream` instance which you'd pass to the `from` function or you can also call it from a custom retry policy. Generally this use case is when you want to cancel a previous stream and subscribe to a new one, otherwise you shouldn't need to.

**Comment by N0N4M3pl** [comment]
> Generally this use case is when you want to cancel a previous stream and subscribe to a new one, 

This is my use case.  
In my app I will write all `from` and `retry` code inside my service - to have better control of this functionality.
